export const CATEGORIES_ACTION_TYPES = {
    // SET_CATEGORIES: 'categories/SET_CATEGORIES',
    SET_CATEGORIES_START: 'categories/SET_CATEGORIES_START',
    SET_CATEGORIES_SUCCESS: 'categories/SET_CATEGORIES_SUCCESS',
    SET_CATEGORIES_FAILED: 'categories/SET_CATEGORIES_FAILED',

}